# Generated by Django 4.2.27 on 2026-01-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('birth_year', models.IntegerField()),
                ('death_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('cover_image', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('publication_year', models.IntegerField()),
                ('description', models.TextField()),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='Litra.writers')),
            ],
        ),
    ]
