# Generated by Django 4.2.27 on 2026-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Litra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writers',
            name='biography',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writers',
            name='quote',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
