# Generated by Django 4.2.27 on 2026-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Litra', '0002_writers_biography_writers_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writers',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writers',
            name='genre',
            field=models.CharField(choices=[('writer', 'Писатель'), ('poet', 'Поэт'), ('dramatist', 'Драматург')], max_length=100),
        ),
    ]
