# Generated by Django 4.2.27 on 2026-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Litra', '0003_alter_writers_death_year_alter_writers_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writers',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
