# Generated by Django 4.2.27 on 2026-01-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Litra', '0004_alter_writers_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='writers',
            name='century',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
