# Generated by Django 4.2.28 on 2026-02-13 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Litra', '0005_writers_century'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writers',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_writers', to=settings.AUTH_USER_MODEL),
        ),
    ]
