# Generated by Django 4.2.28 on 2026-02-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Litra', '0006_works_favorited_by_writers_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='author_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='Litra.writers'),
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание факта')),
                ('period', models.CharField(blank=True, choices=[('17', 'XVII век'), ('18', 'XVIII век'), ('19', 'XIX век'), ('20', 'XX век'), ('21', 'XXI век')], max_length=2, null=True)),
                ('category', models.CharField(choices=[('biography', 'Биография'), ('creative', 'Творчество'), ('trivia', 'Интересное'), ('history', 'Исторический контекст'), ('influence', 'Влияние и наследие'), ('general', 'Общая литература')], default='trivia', max_length=50)),
                ('image_url', models.URLField()),
                ('source', models.CharField(blank=True, max_length=300)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(related_name='likes_facts', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='Litra.works')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='Litra.writers')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'ordering': ['-created_at'],
            },
        ),
    ]
