# Generated by Django 4.2.28 on 2026-02-21 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Litra', '0008_quizz_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facts',
            name='likes',
        ),
        migrations.AddField(
            model_name='facts',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_facts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Litra.question', verbose_name='quizz'),
        ),
    ]
