# Generated by Django 4.2.28 on 2026-02-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Litra', '0009_remove_facts_likes_facts_favorited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Litra.question'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='times_taken',
            field=models.IntegerField(default=0),
        ),
    ]
