# Generated by Django 4.2.28 on 2026-02-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Litra', '0010_alter_answer_question_alter_quizz_times_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
