# Generated by Django 4.2.28 on 2026-02-22 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Litra', '0011_facts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facts',
            name='likes',
        ),
        migrations.AddField(
            model_name='facts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_facts', to=settings.AUTH_USER_MODEL),
        ),
    ]
